name = "cookiecloud"
compatibility_date = "2024-04-29"
main = "src/index.ts"
minify = true
upload_source_maps = true

[placement]
mode = "smart"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cookiecloud"
database_id = "ae1ae5b1-4b0c-44e8-b9ab-170b5d162eb3"

# [ai]
# binding = "AI"
