name: Deploy Worker
on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install
      # Workaround for
      # https://github.com/cloudflare/wrangler-action/issues/199
      # https://github.com/cloudflare/wrangler-action/issues/231
      - name: Set wrangler version
        id: wrangler
        run: echo "version=$(jq -r .devDependencies.wrangler package.json | cut -c2-)" >> "$GITHUB_OUTPUT"
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: ${{ steps.wrangler.outputs.version }}
      - name: Build JS
        run: pnpm run build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: build worker js'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
